fix about dhcp

diff --git a/skylar_ha/manager/iptables b/skylar_ha/manager/iptables
--- a/skylar_ha/manager/iptables
+++ b/skylar_ha/manager/iptables
@@ -28,6 +28,11 @@ prepare() {
         return 1
     fi
 
+    if ! disable_dhcp; then
+        echo "ERROR. disable dhcp failed."
+        return 1
+    fi
+
     return 0
 }
 
@@ -76,24 +81,23 @@ install() {
         return 1
     fi
 
-    if ! disable_dhcp; then
-        echo "ERROR. disable dhcp failed."
-        return 1
-    fi
-
     return 0
 }
 
 
 disable_dhcp() {
     source $WORK_DIR/conf/ha.conf
-    dev=`ip addr | grep -B 2"$master_ip\|$slave_ip" | head -1 | awk {'print $2'} | awk -F ":" {'print $1'}`
-    network_file="/etc/sysconfig/network-scripts/$dev"
+    device=`ip addr | grep -B 2 "$master_ip\|$slave_ip" | head -1 | awk {'print $2'} | awk -F ":" {'print $1'}`
+    network_file="/etc/sysconfig/network-scripts/ifcfg-$device"
+    if [ ! -n $device ]; then
+        network_file=`ls /etc/sysconfig/network-scripts/ifcfg-e* | head -1`
+    fi
     
     cat $network_file | grep "dhcp\|DHCP" >> /dev/null
     if [ $? -eq 0 ]; then
-        echo "WARN. $network_file BOOTPROTO is dhcp. I will config it to static."
-        cp $network_file /etc/sysconfig/backup_network-scripts_$dev
+        echo "WARN. $network_file BOOTPROTO is dhcp. config it to static at first."
+
+        cp $network_file /etc/sysconfig/backup_network-scripts_$device
         sed -i 's/dhcp/static/g' $network_file
         my_ip=$master_ip
         ip addr | grep "slave_ip" >> /dev/null
@@ -108,7 +112,7 @@ NM_CONTROLLED=no #add by skyha script" >> $network_file
         ip addr | grep $my_ip >> /dev/null
         if [ $? -ne 0 ]; then
             echo "ERROR. disable dhcp failed."
-            mv -f /etc/sysconfig/backup_network-scripts_$dev $network_file
+            mv -f /etc/sysconfig/backup_network-scripts_$device $network_file
         else
             echo "OK. dhcp is disable."
         fi
