update function of recover

diff --git a/skylar_ha/resource/beanstalkd b/skylar_ha/resource/beanstalkd
--- a/skylar_ha/resource/beanstalkd
+++ b/skylar_ha/resource/beanstalkd
@@ -94,7 +94,23 @@ failover() {
 }
 
 check_ha_status() {
-    return 0
+    echo "Check Beanstalkd status ..."
+    try=0
+    while [ $try -le 60 ]
+    do
+        pcs cluster unstandby --all
+        crm_mon -Afr -1 | grep bstkd | grep Started
+        if [ $? -eq 0 ]; then
+            echo "OK. Beanstalkd is started."
+            return 0
+        fi
+
+        sleep 1
+        let "try++"
+    done
+    
+    echo "ERROR. Beanstalkd is not started."
+    return 1
 }
 
 recover() {
diff --git a/skylar_ha/resource/pg b/skylar_ha/resource/pg
--- a/skylar_ha/resource/pg
+++ b/skylar_ha/resource/pg
@@ -209,8 +209,23 @@ failover() {
 
 # todo
 check_status() {
-    echo "OK. pg master and slave are running."
-    return 0
+    echo "Check pg status ..."
+    try=0
+    while [ $try -le 60 ]
+    do
+        pcs cluster unstandby --all
+        crm_mon -Afr -1 | grep postgres | grep Started
+        if [ $? -eq 0 ]; then
+            echo "OK. PG is started."
+            return 0
+        fi
+
+        sleep 1
+        let "try++"
+    done
+    
+    echo "ERROR. PG is not started."
+    return 1
 }
 
 source $WORK_DIR/conf/ha.conf
diff --git a/skylar_ha/resource/redis b/skylar_ha/resource/redis
--- a/skylar_ha/resource/redis
+++ b/skylar_ha/resource/redis
@@ -104,7 +104,23 @@ failover() {
 }
 
 check_ha_status() {
-    return 0
+    echo "Check redis status ..."
+    try=0
+    while [ $try -le 60 ]
+    do
+        pcs cluster unstandby --all
+        crm_mon -Afr -1 | grep redis | grep Started
+        if [ $? -eq 0 ]; then
+            echo "OK. Redis is started."
+            return 0
+        fi
+
+        sleep 1
+        let "try++"
+    done
+    
+    echo "ERROR. Redis is not started."
+    return 1
 }
 
 recover() {
diff --git a/skylar_ha/skyha b/skylar_ha/skyha
--- a/skylar_ha/skyha
+++ b/skylar_ha/skyha
@@ -307,6 +307,11 @@ reset() {
 # invoke the resouce's recover method. recover resouce back to ha status.
 #
 recover() {
+    if check_ha_status; then
+        echo "OK. HA status is correct. Do nothing."
+        return 0
+    fi
+
     date
     try=0
     while [ $try -le 5 ]
@@ -324,6 +329,7 @@ recover() {
 
     systemctl start docker.service
 
+
     if ! master_is_work; then
         recover_master
     elif ! slave_is_work; then
@@ -336,6 +342,7 @@ recover() {
 
     if [ $? -ne 0 ]; then
         echo "ERROR. Recover failed. `date`"
+        return 1
     fi
 
     echo "Done. Recover finished at time: `date`"
@@ -400,10 +407,24 @@ recover_master() {
     drbdadm connect all
 
     systemctl start pacemaker.service
+    sleep 1
+    pcs cluster unstandby --all
 
     return 0
 }
 
+recover_slave() {
+    for file in $WORK_DIR/resource/*
+    do
+        if [ -f $file ]; then
+            $file "recover"
+            if [ $? -ne 0 ]; then
+                echo "ERROR. Execute $file recover failed."
+                return 1
+            fi
+        fi
+    done
+}
 
 #
 # check args and install just for one host.
