update

diff --git a/skylar_ha/resource/beanstalkd b/skylar_ha/resource/beanstalkd
--- a/skylar_ha/resource/beanstalkd
+++ b/skylar_ha/resource/beanstalkd
@@ -44,13 +44,13 @@ install_bstkd() {
         docker rm $BSTKD_CONTAINER
     fi
 
-    docker run --name=$BSTKD_CONTAINER --restart=always -d --net=host --privileged=true $BSTKD_IMAGE_NAME
-    if ! is_bstkd_run; then
-        echo "ERROR. Start beanstalkd failed."
-        return 1
-    fi
-    docker stop $BSTKD_CONTAINER
-    echo "OK. Install beanstalkd succeed."
+    #docker run --name=$BSTKD_CONTAINER --restart=always -d --net=host --privileged=true $BSTKD_IMAGE_NAME
+    #if ! is_bstkd_run; then
+    #    echo "ERROR. Start beanstalkd failed."
+    #    return 1
+    #fi
+    #docker stop $BSTKD_CONTAINER
+    #echo "OK. Install beanstalkd succeed."
     return 0
 }
 
@@ -82,7 +82,7 @@ is_bstkd_run() {
 failover() {
     pcs -f resource_cfg resource create bstkd docker image=$BSTKD_IMAGE_NAME:latest \
         run_opts="--net=host --privileged=true" name="$BSTKD_CONTAINER" \
-        monitor_cmd="ps -ef | grep beanstalkd >/dev/null" \
+        monitor_cmd="ps -ef | grep beanstalkd " \
         op start timeout="60s" interval="0s" on-fail="restart" \
         op monitor timeout="60s" interval="5s" on-fail="restart" \
         op stop timeout="60s" interval="0s" on-fail="block"
diff --git a/skylar_ha/resource/pg b/skylar_ha/resource/pg
--- a/skylar_ha/resource/pg
+++ b/skylar_ha/resource/pg
@@ -65,18 +65,18 @@ install_pg() {
         docker rm $PG_CONTAINER
     fi
 
-    docker run -d --net=host --privileged=true --name "$PG_CONTAINER" --restart=always "$PG_IMAGE_NAME"
+    #docker run -d --net=host --privileged=true --name "$PG_CONTAINER" --restart=always "$PG_IMAGE_NAME"
 
-    if [ $? -ne 0 ]; then
-        echo "ERROR. docke run failed, cmd: docker run -d --net=host --privileged=true --name $PG_CONTAINER --restart=always $PG_IMAGE_NAME"
-        return 1
-    fi
+    #if [ $? -ne 0 ]; then
+    #    echo "ERROR. docke run failed, cmd: docker run -d --net=host --privileged=true --name $PG_CONTAINER --restart=always $PG_IMAGE_NAME"
+    #    return 1
+    #fi
 
-    if ! check_pg_run; then
-        echo "ERROR. PG is not running."
-        return 1
-    fi
-    docker stop $PG_CONTAINER
+    #if ! check_pg_run; then
+    #    echo "ERROR. PG is not running."
+    #    return 1
+    #fi
+    #docker stop $PG_CONTAINER
     return 0
 }
 
diff --git a/skylar_ha/resource/redis b/skylar_ha/resource/redis
--- a/skylar_ha/resource/redis
+++ b/skylar_ha/resource/redis
@@ -54,14 +54,14 @@ install_redis() {
         docker rm $REDIS_CONTAINER
     fi
 
-    docker run --name=$REDIS_CONTAINER -d --net=host --privileged=true $REDIS_IMAGE_NAME
-    if ! is_redis_run; then
-        echo "ERROR. Start redis failed."
-        return 1
-    fi
-    docker stop $REDIS_CONTAINER
+    #docker run --name=$REDIS_CONTAINER -d --net=host --privileged=true $REDIS_IMAGE_NAME
+    #if ! is_redis_run; then
+    #    echo "ERROR. Start redis failed."
+    #    return 1
+    #fi
+    #docker stop $REDIS_CONTAINER
 
-    echo "OK. Install redis succeed."
+    #echo "OK. Install redis succeed."
     return 0
 }
 
