安装pg后，检查pg运行状态

diff --git a/skylar_ha/resource/drbd b/skylar_ha/resource/drbd
--- a/skylar_ha/resource/drbd
+++ b/skylar_ha/resource/drbd
@@ -101,6 +101,13 @@ install() {
 }
 
 set_master() {
+    sleep 2
+    cat /proc/drbd | grep 'cs:Connected' | grep 'ro:Secondary/Secondary'
+    if [ $? -ne 0 ]; then
+        echo "ERROR. drbd are not connected between master and slave."
+        return 1
+    fi
+
     drbdadm primary --force skydata
 
     try=0
diff --git a/skylar_ha/resource/pg b/skylar_ha/resource/pg
--- a/skylar_ha/resource/pg
+++ b/skylar_ha/resource/pg
@@ -72,6 +72,11 @@ install_pg() {
         return 1
     fi
 
+    if ! check_pg_run; then
+        echo "ERROR. PG is not running."
+        return 1
+    fi
+
     return 0
 }
 
